# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'Anti-Entropy' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Anti-Entropy
    pod 'RxSwift', '~> 4.0'
    pod 'RxCocoa', '~> 4.0'
    pod "RxRealm"
    pod 'Default'

  target 'Anti-EntropyTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
